### ISSUE TITLE
[Bug]: @cache decorator obscures method annotation

### ISSUE THREAD

**Issue by stinovlas** [maxfischer2781/asyncstdlib#161]
### What happened?

When I run `mypy==1.12.0` on the example below, I get following errors:

```
testtyping.py:12: error: Returning Any from function declared to return "int"  [no-any-return]
testtyping.py:12: error: No overload variant of "__get__" of "LRUAsyncCallable" matches argument types "A", "type[A]"  [call-overload]
testtyping.py:12: note: Possible overload variant:
testtyping.py:12: note:     def __get__(self, instance: None, owner: type | None = ...) -> LRUAsyncCallable[Callable[[A, int], Coroutine[Any, Any, int]]]
```

Without the `@cache` decorator, there are no mypy errors. I'd expect the decorator to preserve the method annotation.

### Minimal Reproducible Example

```python
from asyncstdlib import cache

class A:
    @cache
    async def func(self, x: int) -> int:
        return x + 1

    async def my_func(self) -> int:
        return await self.func(5)
```

### Request Assignment [Optional]

- [ ] I already understand the cause and want to submit a bugfix.

**Comment by maxfischer2781** [comment]
This looks like a recent regression. Things are working fine with MyPy 1.10. I have to double check whether it's an issue on the MyPy side.

**Comment by maxfischer2781** [comment]
[The MyPy were very quick to fix this.](https://github.com/python/mypy/pull/18040) This should be resolved with the next MyPy release.

**Comment by stinovlas** [comment]
> [The MyPy folks were very quick to fix this.](https://github.com/python/mypy/pull/18040) This should be resolved with the next MyPy release.

Looks good :-). Thanks for your attention.
